hl.on("hyprland.start", function ()
	hl.exec_cmd("ashell --config-path ~/.config/hypr/ashell/config.toml")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("protonvpn connect")
	hl.exec_cmd("easyeffects -w --service-mode")
end)
